//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public long BookID { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> YearReleased { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
    }
}
